import { Category, Product, PaymentMethod, User, Address, Order } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Semua Kategori",
    slug: "semua",
    icon: "LayoutGrid",
    description: "Jelajahi seluruh koleksi produk terlengkap di PASARLORE Toko Serba Ada",
  },
  {
    id: "cat-2",
    name: "Elektronik & Gadget",
    slug: "elektronik-gadget",
    icon: "Smartphone",
    description: "Perangkat elektronik, audio, aksesoris gadget, dan perkakas pintar",
  },
  {
    id: "cat-3",
    name: "Kebutuhan Rumah Tangga",
    slug: "kebutuhan-rumah-tangga",
    icon: "Home",
    description: "Consumer goods, sabun pembersih, deterjen, dan perlengkapan rumah harian",
  },
  {
    id: "cat-4",
    name: "Makanan & Minuman",
    slug: "makanan-minuman",
    icon: "Coffee",
    description: "Snack lezat, kopi pilihan, susu, bumbu, dan bahan pangan berkualitas",
  },
  {
    id: "cat-5",
    name: "Fashion & Gaya Hidup",
    slug: "fashion-aksesoris",
    icon: "Shirt",
    description: "Pakaian kasual, tas fungsional, jam tangan, dan aksesoris harian",
  },
  {
    id: "cat-6",
    name: "Kesehatan & Perawatan",
    slug: "kesehatan-kecantikan",
    icon: "Sparkles",
    description: "Skincare, suplemen vitamin, perlengkapan mandi, dan produk kebugaran",
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    sku: "SKU-ELK-001",
    name: "TWS True Wireless Earbuds Pro Noise Cancelling",
    slug: "tws-true-wireless-earbuds-pro",
    description: "Earphone nirkabel Bluetooth 5.3 dengan Active Noise Cancellation (ANC), bass bertenaga, daya tahan baterai hingga 30 jam bersama casing pengisi daya, dan mikrofon jernih untuk panggilan kerja maupun hiburan.",
    price: 289000,
    stock: 35,
    categoryId: "cat-2",
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Unit (Box)",
    rating: 4.9,
    soldCount: 430,
    createdAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "prod-2",
    sku: "SKU-ELK-002",
    name: "Fast Charging Powerbank 20.000mAh 65W PD",
    slug: "powerbank-20000mah-fast-charging",
    description: "Powerbank kapasitas jumbo 20.000mAh mendukung pengisian daya super cepat Power Delivery (PD) & Quick Charge 3.0. Dilengkapi LED display indikator baterai dan aman dibawa ke kabin pesawat.",
    price: 245000,
    stock: 22,
    categoryId: "cat-2",
    imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Unit",
    rating: 4.8,
    soldCount: 310,
    createdAt: "2026-08-02T09:00:00Z",
  },
  {
    id: "prod-3",
    sku: "SKU-ELK-003",
    name: "Smart LED Desk Lamp Dimmable Eye Care",
    slug: "smart-led-desk-lamp-eye-care",
    description: "Lampu meja belajar pintar dengan 3 mode temperatur cahaya (warm, natural, cool white), sensor sentuh kecerahan fleksibel, dan teknologi anti flicker yang ramah untuk mata saat bekerja malam.",
    price: 135000,
    stock: 18,
    categoryId: "cat-2",
    imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Unit",
    rating: 4.7,
    soldCount: 165,
    createdAt: "2026-08-03T10:00:00Z",
  },
  {
    id: "prod-4",
    sku: "SKU-CGD-001",
    name: "Deterjen Cair Konsentrat Anti Bakteri 1.8 Liter",
    slug: "deterjen-cair-konsentrat-anti-bakteri",
    description: "Formula konsentrat berteknologi jepang efektif mengangkat noda membandel pada pakaian putih dan berwarna. Menghilangkan bau apek dengan keharuman bunga sakura segar tahan 48 jam.",
    price: 38500,
    stock: 65,
    categoryId: "cat-3",
    imageUrl: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Pouch (1.8 L)",
    rating: 4.9,
    soldCount: 820,
    createdAt: "2026-08-04T11:00:00Z",
  },
  {
    id: "prod-5",
    sku: "SKU-CGD-002",
    name: "Sabun Cuci Piring Ekstrak Jeruk Nipis 1600ml",
    slug: "sabun-cuci-piring-jeruk-nipis",
    description: "Cairan pencuci piring dengan kekuatan ekstrak jeruk nipis asli yang meluruhkan lemak membandel seketika, lembut di tangan, dan higienis untuk mencuci buah serta sayuran.",
    price: 26000,
    stock: 80,
    categoryId: "cat-3",
    imageUrl: "https://images.unsplash.com/photo-1585751119414-ef2636f8aede?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Pouch (1600ml)",
    rating: 4.8,
    soldCount: 940,
    createdAt: "2026-08-05T07:30:00Z",
  },
  {
    id: "prod-6",
    sku: "SKU-CGD-003",
    name: "Cairan Pembersih Lantai Aroma French Lavender 800ml",
    slug: "cairan-pembersih-lantai-lavender",
    description: "Pembersih lantai antibakteri 99.9% membunuh kuman penyebab penyakit. Memberikan kilau bersih tanpa lengket dan aroma lavender yang menenangkan di seluruh ruangan.",
    price: 15500,
    stock: 50,
    categoryId: "cat-3",
    imageUrl: "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Pouch (800ml)",
    rating: 4.8,
    soldCount: 520,
    createdAt: "2026-08-06T08:15:00Z",
  },
  {
    id: "prod-7",
    sku: "SKU-FNB-001",
    name: "Kopi Arabika Single Origin Gayo 250g Roast Beans",
    slug: "kopi-arabika-gayo-single-origin",
    description: "Biji kopi Arabika murni dari dataran tinggi Takengon Gayo Aceh. Memiliki citarasa khas notes caramel, fruity acidity yang seimbang, dan aroma wangi semerbak.",
    price: 68000,
    stock: 28,
    categoryId: "cat-4",
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Pack (250g)",
    rating: 5.0,
    soldCount: 290,
    createdAt: "2026-08-07T09:20:00Z",
  },
  {
    id: "prod-8",
    sku: "SKU-FNB-002",
    name: "Madu Hutan Murni Nusantara 500g Alami",
    slug: "madu-hutan-murni-nusantara",
    description: "Madu mentah (raw honey) murni hasil panen lebah hutan liar tanpa proses pemanasan atau campuran pemanis buatan. Kaya enzim dan antioksidan untuk meningkatkan imunitas tubuh.",
    price: 85000,
    stock: 15,
    categoryId: "cat-4",
    imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Botol (500g)",
    rating: 4.9,
    soldCount: 380,
    createdAt: "2026-08-08T09:45:00Z",
  },
  {
    id: "prod-9",
    sku: "SKU-FNB-003",
    name: "Beras Pandan Wangi Pulen Cianjur 5 Kg",
    slug: "beras-pandan-wangi-cianjur-5kg",
    description: "Beras aromatik pandan wangi asli Cianjur kualitas premium tanpa pemutih atau pengawet. Menghasilkan nasi lembut, wangi, dan pulen untuk keluarga.",
    price: 79500,
    stock: 40,
    categoryId: "cat-4",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Karung (5 Kg)",
    rating: 4.9,
    soldCount: 650,
    createdAt: "2026-08-09T10:10:00Z",
  },
  {
    id: "prod-10",
    sku: "SKU-FSH-001",
    name: "Kaos Polos Premium Cotton Combed 24s Heavyweight",
    slug: "kaos-polos-cotton-combed-24s",
    description: "T-shirt basic unisex berbahan 100% katun combed 24s berkualitas tinggi. Jahitan rantai rapi, bahan tebal tidak menerawang namun tetap sejuk dan nyaman dipakai sepanjang hari.",
    price: 55000,
    stock: 75,
    categoryId: "cat-5",
    imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Pcs",
    rating: 4.8,
    soldCount: 510,
    createdAt: "2026-08-10T11:00:00Z",
  },
  {
    id: "prod-11",
    sku: "SKU-FSH-002",
    name: "Tas Ransel Laptop Anti Air Casual Backpack",
    slug: "tas-ransel-laptop-waterproof",
    description: "Backpack modern dengan kompartemen laptop hingga 15.6 inch berbusa tebal, material cordura water-repellent tahan cipratan hujan, dan port USB charger eksternal.",
    price: 175000,
    stock: 12,
    categoryId: "cat-5",
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Pcs",
    rating: 4.8,
    soldCount: 220,
    createdAt: "2026-08-11T13:00:00Z",
  },
  {
    id: "prod-12",
    sku: "SKU-KEC-001",
    name: "Sunscreen Gel UV Shield SPF 50+ PA++++ 50ml",
    slug: "sunscreen-gel-uv-shield-spf50",
    description: "Tabir surya bertekstur gel ringan tanpa white-cast, cepat meresap, dan non-comedogenic. Memberikan perlindungan maksimal dari sinar UVA/UVB dan polusi harian.",
    price: 62000,
    stock: 45,
    categoryId: "cat-6",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    isActive: true,
    unit: "Botol (50ml)",
    rating: 4.9,
    soldCount: 780,
    createdAt: "2026-08-12T14:30:00Z",
  },
];

export const MOCK_PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: "pm-1",
    bankName: "Bank Central Asia (BCA)",
    accountNumber: "8830192841",
    accountHolder: "PASARLORE INDONESIA",
    instructions: "Transfer sesuai nominal hingga 3 digit terakhir. Simpan dan upload foto bukti transfer.",
    isActive: true,
  },
  {
    id: "pm-2",
    bankName: "Bank Mandiri",
    accountNumber: "1370019283741",
    accountHolder: "PASARLORE INDONESIA",
    instructions: "Lakukan transfer via Mandiri Livin atau ATM ke nomor rekening tujuan resmi PASARLORE.",
    isActive: true,
  },
  {
    id: "pm-3",
    bankName: "Bank Rakyat Indonesia (BRI)",
    accountNumber: "020601009847503",
    accountHolder: "PASARLORE INDONESIA",
    instructions: "Transfer melalui BRImo atau ATM BRI. Konfirmasi pembayaran dengan mengunggah struk.",
    isActive: true,
  },
];

export function formatRupiah(amount: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}
